@Any_Issues_HostAddress = https://localhost:7108
@issueNumber = 1

GET {{Any_Issues_HostAddress}}/api/v1/bitbucket/issues
Accept: application/json

###

GET {{Any_Issues_HostAddress}}/api/bitbucket/issues
Accept: application/json

###

POST {{Any_Issues_HostAddress}}/api/v1/bitbucket/issues
Accept: application/json

{
    "title": "New Api Post Issue WITH DESCRIPTION!",
    "content":
    {
        "raw": "This is a new issue created via my API."
    }
}

###

PUT {{Any_Issues_HostAddress}}/api/v1/bitbucket/issues/{{issueNumber}}
Accept: application/json

{
    "title": "Modified issue WITH DESCRIPTION!",
    "content":
    {
        "raw": "Modified by API."
    }
}

###

DELETE {{Any_Issues_HostAddress}}/api/v1/bitbucket/issues/{{issueNumber}}
Accept: application/json